"""empty message

Revision ID: 3127d8063922
Revises: 8420d2590e0c
Create Date: 2022-11-09 02:21:52.204332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3127d8063922'
down_revision = '8420d2590e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ingredient', 'ingredient_serving_unit', ['serving_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    # ### end Alembic commands ###
