"""empty message

Revision ID: 8420d2590e0c
Revises: 35f977abe797
Create Date: 2022-11-03 15:19:48.211942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8420d2590e0c'
down_revision = '35f977abe797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('default_serving_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'ingredient_serving_unit', ['default_serving_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'default_serving_unit_id')
    # ### end Alembic commands ###
