"""empty message

Revision ID: 0222a082cff4
Revises: b6c4dbfcf379
Create Date: 2022-08-26 13:16:51.743235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0222a082cff4'
down_revision = 'b6c4dbfcf379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_standard_name', sa.String(), nullable=True))
    op.drop_column('ingredient', 'ingredient_other_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient_other_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ingredient', 'ingredient_standard_name')
    # ### end Alembic commands ###
