"""empty message

Revision ID: 08ff43784cd1
Revises: 7da0e3bdfa7a
Create Date: 2022-08-26 14:46:13.350789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ff43784cd1'
down_revision = '7da0e3bdfa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_nutrition', sa.Column('macros', sa.JSON(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('micros', sa.JSON(), nullable=True))
    op.drop_column('ingredient_nutrition', 'nutrition_name')
    op.drop_column('ingredient_nutrition', 'nutrition_type')
    op.drop_column('ingredient_nutrition', 'nutrition_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_nutrition', sa.Column('nutrition_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('nutrition_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('nutrition_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ingredient_nutrition', 'micros')
    op.drop_column('ingredient_nutrition', 'macros')
    # ### end Alembic commands ###
