"""empty message

Revision ID: 18cd60cfe4bc
Revises: d9375c92d3a7
Create Date: 2022-08-24 17:42:34.653877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cd60cfe4bc'
down_revision = 'd9375c92d3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_serving_unit', sa.Column('serving_unit_othername', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_serving_unit', 'serving_unit_othername')
    # ### end Alembic commands ###
