"""empty message

Revision ID: 1c4c36545430
Revises: 18cd60cfe4bc
Create Date: 2022-08-24 20:42:41.518961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4c36545430'
down_revision = '18cd60cfe4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'nin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient', 'nin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
