"""empty message

Revision ID: 467c512257ac
Revises: 49fd15281b21
Create Date: 2022-08-22 15:07:12.323961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467c512257ac'
down_revision = '49fd15281b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=True),
    sa.Column('auth_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_auth_key'), 'auth', ['auth_key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_auth_key'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
