"""empty message

Revision ID: 55530f152f9f
Revises: 08ff43784cd1
Create Date: 2022-08-26 17:17:02.003153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55530f152f9f'
down_revision = '08ff43784cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('planned_by', sa.Integer(), nullable=True),
    sa.Column('planned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['plan_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_meal')
    # ### end Alembic commands ###
