"""empty message

Revision ID: 6231cff1dfd2
Revises: 
Create Date: 2022-09-02 15:03:41.282202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6231cff1dfd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=True),
    sa.Column('auth_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_auth_key'), 'auth', ['auth_key'], unique=True)
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_week_number', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_serving_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serving_unit_name', sa.String(), nullable=True),
    sa.Column('serving_unit_othername', sa.String(), nullable=True),
    sa.Column('serving_unit_quantity', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nin_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nin_code', sa.String(length=255), nullable=True),
    sa.Column('ingredient_name', sa.Text(), nullable=True),
    sa.Column('ingredient_description', sa.JSON(), nullable=True),
    sa.Column('macros', sa.JSON(), nullable=True),
    sa.Column('micros', sa.JSON(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nin_ingredient_nin_code'), 'nin_ingredient', ['nin_code'], unique=True)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('course', sa.JSON(), nullable=True),
    sa.Column('cusine', sa.JSON(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.Column('website_name', sa.String(), nullable=True),
    sa.Column('serving', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timing_label', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('nin_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_standard_name', sa.String(), nullable=True),
    sa.Column('ingredient_desc', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_in_gram', sa.Integer(), nullable=True),
    sa.Column('serving_unit_id', sa.Integer(), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('macros', sa.JSON(), nullable=True),
    sa.Column('micros', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nin_id'], ['nin_ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['timing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_meal',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['plan_schedule.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_meal')
    op.drop_table('plan_schedule')
    op.drop_table('ingredient')
    op.drop_table('user')
    op.drop_table('timing')
    op.drop_table('recipe')
    op.drop_table('plan')
    op.drop_index(op.f('ix_nin_ingredient_nin_code'), table_name='nin_ingredient')
    op.drop_table('nin_ingredient')
    op.drop_table('ingredient_serving_unit')
    op.drop_table('day')
    op.drop_index(op.f('ix_auth_auth_key'), table_name='auth')
    op.drop_table('auth')
    # ### end Alembic commands ###
