"""empty message

Revision ID: 7da0e3bdfa7a
Revises: 0222a082cff4
Create Date: 2022-08-26 13:25:28.479985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da0e3bdfa7a'
down_revision = '0222a082cff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('nutrition_type', sa.String(), nullable=True),
    sa.Column('nutrition_name', sa.String(), nullable=True),
    sa.Column('nutrition_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_nutrition')
    # ### end Alembic commands ###
