"""empty message

Revision ID: d318367a4dfb
Revises: 57790a617027
Create Date: 2022-08-23 11:29:10.234994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd318367a4dfb'
down_revision = '57790a617027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NIN__ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nin_code', sa.String(length=255), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=True),
    sa.Column('ingredient_description', sa.String(length=500), nullable=True),
    sa.Column('macros', sa.JSON(), nullable=True),
    sa.Column('micros', sa.JSON(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NIN__ingredient_nin_code'), 'NIN__ingredient', ['nin_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_NIN__ingredient_nin_code'), table_name='NIN__ingredient')
    op.drop_table('NIN__ingredient')
    # ### end Alembic commands ###
