"""empty message

Revision ID: d9375c92d3a7
Revises: 14c05dd3f121
Create Date: 2022-08-24 16:15:57.257900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9375c92d3a7'
down_revision = '14c05dd3f121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_serving_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serving_unit_name', sa.String(), nullable=True),
    sa.Column('serving_unit_quantity', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('course', sa.JSON(), nullable=True),
    sa.Column('cusine', sa.JSON(), nullable=True),
    sa.Column('recipe_url', sa.String(), nullable=True),
    sa.Column('website_name', sa.String(), nullable=True),
    sa.Column('serving', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('nin_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_desc', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_in_gram', sa.Integer(), nullable=True),
    sa.Column('serving_unit_id', sa.Integer(), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nin_id'], ['nin_ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    op.drop_table('recipe')
    op.drop_table('ingredient_serving_unit')
    # ### end Alembic commands ###
