"""empty message

Revision ID: dda42fda6e5f
Revises: 55530f152f9f
Create Date: 2022-08-26 20:42:58.063510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dda42fda6e5f'
down_revision = '55530f152f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planned_meal', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('planned_meal', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('planned_meal', 'id')
    op.drop_column('planned_meal', 'planned_by')
    op.drop_column('planned_meal', 'planned_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_meal', sa.Column('planned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('planned_meal', sa.Column('planned_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('planned_meal', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('planned_meal', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('planned_meal', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
